# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: contrast
locale: "en"
title: Viktor Stubbfält
title_separator: "-"
#subtitle: "Dream it. Build it."
name: "Viktor Stubbfält"
description: >- # this means to ignore newlines until "baseurl:"
  Hello and welcome to my personal site! As you may see, much is still under
  construction. In the future this site will be used as my personal portfolio
  to share interesting projects I have worked on. Enjoy your stay ❤️
url: "https://stubbfalt.com/"
#baseurl: ""
repository: "StoicAurora/StoicAurora.github.io"
#head_scripts:
#teaser:
logo: "/assets/images/logo.png"
masthead_title: " "
#breadcrumbs: true  # disabled by default
date_format: "%Y-%m-%d"
email: viktor@stubbfalt.com
twitter_username: StoicAurora
github_username: StoicAurora

search: false

# Build settings
markdown: kramdown

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /blog/page:num
timezone: Europe/Stockholm

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Viktor Stubbfält"
  avatar : "/assets/images/pfp4.png"
  bio    : "IT-Engineering student at Uppsala University and (astro)photographer from the land of the midnight sun."
  location: "Uppsala, Sweden"
  links:
    # - label: "Website (that's here!)"
    #   icon: "fas fa-fw fa-link"
    #   url: "https://stubbfalt.com"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:viktor@stubbfalt.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/StoicAurora"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/viktorstubb/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/StoicAurora"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/viktorstubb"

atom_feed:
  hide: true
# footer:
#   links:
#     - label: "GitHub"
#       icon: "fab fa-fw fa-github"
#       url: "https://github.com/StoicAurora"
#     - label: "LinkedIn"
#       icon: "fab fa-fw fa-linkedin"
#       url: "https://www.linkedin.com/in/viktorstubb/"
#     - label: "Twitter"
#       icon: "fab fa-fw fa-twitter-square"
#       url: "https://twitter.com/StoicAurora"
#     - label: "Instagram"
#       icon: "fab fa-fw fa-instagram"
#       url: "https://instagram.com/viktorstubb"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      show_date: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

github: [metadata]
