# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Viktor Stubbfält
email: viktor.stubbfalt@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Hello and welcome to my personal site! As you may see, much is still under
  construction. In the future this site will be used as my personal portfolio
  to share interesting projects I have worked on. Enjoy your stay ❤️
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://stubbfalt.com" # the base hostname & protocol for your site, e.g. http://stubbfalt.com
twitter_username: StoicAurora
github_username:  StoicAurora
instagram_username: viktorstubb

# Build settings
markdown: kramdown
theme: minima
skin: dark
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
